name: Transafe Deploy to server

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install 

    - name: Cleanup previous build
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        remoteUser: ${{ secrets.REMOTE_USER }}
        ARGS: "-r"
        SCRIPT_BEFORE: "sudo rm -rf /var/www/TranSafe-Frontend/Render"
      with:
        SOURCE: "./TranSafe-Frontend/dist"
        TARGET: "/var/www/TranSafe-Frontend/Render"
        EXCLUDE: ".git/*, /node_modules"

    - name: Build the app
      run: npm run build

    - name: Deploy Transafe to server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        ARGS: "-rltgoDzvO --delete"
      with:
        SOURCE: "./TranSafe-Frontend/dist"
        TARGET: "/var/www/TranSafe-Frontend/Render"
        EXCLUDE: ".git/*, /node_modules"

    - name: Start Nginx
      uses: appleboy/ssh-action@master
      with:
        command: "sudo systemctl start nginx"
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        port: ${{ secrets.REMOTE_PORT }}
        
